learning_users/basic_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
app_name = 'basic_app'

urlpatterns = [
    
url(r'^login/$',views.user_login,name='user_login'),
url(r'^registration/$',views.registration,name='registration'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name = 'index'),
    path('admin/', admin.site.urls),
    # url(r'^login/$',views.user_login,name='user_login'),
    url(r'^logout/$',views.user_logout,name='user_logout'),
    url(r'^basic_app/',include("basic_app.urls"))

]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

#additional classes
    portfolio = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to ='profile_pics',blank= True )

#because we have used upload to profile_pics.......we have to make a floder in media 
    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    Password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo 
        fields = ('portfolio','profile_pic') 

learning_users/basic_app/views.py
from django.shortcuts import redirect, render
from basic_app.forms  import UserForm,UserProfileForm

from django.contrib.auth import login, logout,authenticate
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required 

# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')



# def login_form(request):
#     return render(request,'basic_app/login.html')





def registration(request):
    registered  = False
    if request.method =='POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileForm(data = request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user
            
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
                
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,'basic_app/registration.html',
    {
        "user_form" : user_form,
        "profile_form":profile_form,
        "registered":registered,

    })
# return render(request,'basic_app/registration.html')



def user_login(request):
    hello = True
    logged = False
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username,password=password)
        if user:
            if user.is_active :
                login(request,user)
                logged = True
                return HttpResponseRedirect(reverse('index'),{"logged":logged})
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')

        else:
            hello = False
            return HttpResponse("Wrong Credentials")
    else:
         return render(request,'basic_app/login.html')
    
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

learning_users/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>  BASE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index'%}">HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'admin:index'%}">ADMIN</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
              <a class="nav-link" href="{%url 'user_logout'%}">LOGOUT</a>
        </li>
        {% else %}
          <li class="nav-item">
          <a class="nav-link" href="{%url 'basic_app:user_login'%}">LOGIN</a>


        </li>
        {% endif %}

        <li class="nav-item">
          <a class="nav-link" href="{%url 'basic_app:registration'%}">SIGN_UP</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<div class="container">
  {% block body_block %}

{% endblock %}
</div>
  </body>
</html>

learning_users/learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{%block body_block%}

    <div class="jumbotron">
      <h1>DJANGO LEVEL 5</h1>
      
    </div>

{% endblock %}

learning_users/learning_users/templates/basic_app/login.html
<!DOCTYPE>
{% extends 'basic_app/base.html' %}
{% block body_block%}
<div class ="jumbotron">
<form action="{% url 'basic_app:user_login' %}" method="post">
  {% csrf_token%}

  <div class="container">
  <p>
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required>
    </p>

    <p>
    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>
    </p>

    <button type="submit">Login</button>
    <label>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
  </div>


</form>

</div>
{% endblock %}

learning_users/learning_users/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends 'basic_app/base.html'%}


{% block body_block %}

<div class="jumbotron">
{% if registered %}
    <h1>ThankYou For Registering</h1>
 {%else%}
 <h1>Fill Out The Form</h1>
  <form   enctype="multipart/form-data"  method="post">
              {% csrf_token %}
              {{user_form.as_p}}
              {{profile_form.as_p}}
              <input type="submit" name="" value="registration">

  </form>
{% endif %}
</div>


{% endblock %}